### ISSUE TITLE
Instellen standaard valuta niet mogelijk door conflict met met laatste Gravity Forms versies

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-gravityforms-nl#5]
Deze plugin zorgt voor een conflict met Gravity Forms, waardoor je de standaard valuta niet kunt instellen op Euro.
Deze springt na instellen weer naar Amerikaanse Dollar.

Volgens mij onderhouden we deze plugin niet meer actief. Maar staat deze wel op meerdere sites actief, zoals revalidatie-friesland.nl en paulusma.nl.

We kunnen deze plugin bijwerken zodat deze weer goed werkt met nieuwere Gravity Forms versies. Of we moeten de bestaande installaties even nalopen en deze plugin verwijderen. Daarbij is het denk ik belangrijkste dat bij productvelden het euro-teken voor de bedragen blijft staan: https://docs.gravityforms.com/gform_currencies/#h-1-update-euro

**Comment by remcotolsma** [comment]
We still actively maintain this plugin/library, it's also included in the Pronamic Pay plugin: https://github.com/pronamic/wp-pronamic-pay/blob/2176fa4356efd063855efdd75f2ee70ab6938d5d/composer.json#L61. The problem no longer occurs in the current codebase, but on a number of sites an older version of this plugin is still running. Because the plugin has been closed on WordPress.org, updates are no longer available via this platform: https://wordpress.org/plugins/gravityforms-nl/. I just pushed the release to the https://wp.pronamic.directory/ platform so the update is available via the Pronamic Client plugin.

<img width="936" alt="Scherm­afbeelding 2023-08-21 om 11 35 50" src="https://github.com/pronamic/wp-gravityforms-nl/assets/869674/d8e488d6-2c32-47bd-a8aa-20798dea2b83">
